# fly.toml file generated for anicetnougaret-protohackers-in-elixir on 2023-01-31T09:14:15+01:00

app = "anicetnougaret-protohackers-in-elixir"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
internal_port = 5001
protocol = "tcp"
  
[[services.ports]]
handlers = []
port = 5001

[[services]]
internal_port = 5002
protocol = "tcp"
  
[[services.ports]]
handlers = []
port = 5002

[[services]]
internal_port = 5003
protocol = "tcp"
  
[[services.ports]]
handlers = []
port = 5003

[[services]]
internal_port = 5004
protocol = "tcp"
  
[[services.ports]]
handlers = []
port = 5004

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
